cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('remove/<int:product_id>/', views.remove, name='remove'),
    path('delete/<int:product_id>/', views.delete, name='delete'),
]

ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('', views.SearchResult, name="SearchResult"),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    # path('a/', views.home, name="home"),
    path('', views.allProdCat, name="allProdCat"),
    path('<slug:c_slug>/', views.allProdCat, name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/',
         views.proDetail, name="prodCatDetail")
]

cart/models.py
from operator import mod
from django.db import models
from shop.models import product

# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=20, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    Product = models.ForeignKey(product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def subtotal(self):
        return self.Product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.Product)

search_app/models.py
from django.db import models

# Create your models here.

shop/models.py
from distutils.command.upload import upload
from django.db import models
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:prodCatDetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

cart/views.py
import imp
from django.shortcuts import get_object_or_404, redirect, render
from shop.models import product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    Product = product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(Product=Product, cart=cart)
        if cart_item.quantity < cart_item.Product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            Product=Product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.Product.price * cart_item.quantity)
            counter += cart_item.quantity

    except:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    Product = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, Product=Product)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def delete(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    Product = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, Product=Product)
    cart_item.delete()
    return redirect('cart:cart_detail')

search_app/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import Q
# Create your views here.


def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = product.objects.all().filter(
            Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import product, Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage
# Create your views here.


def allProdCat(request, c_slug=None):
    cat = None
    products_list = None
    paginator = None
    if c_slug != None:
        cat = get_object_or_404(Category, slug=c_slug)
        products_list = product.objects.all().filter(category=cat, available=True)
    else:
        products_list = product.objects.all().filter(available=True)
        paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = Paginator(products_list, 6).page(page)
    except (EmptyPage, InvalidPage):
        products = Paginator(products_list, 6).page(
            Paginator(products_list, 6).num_pages)
    return render(request, 'category.html', {'category': cat, 'products': products})


def proDetail(request, c_slug, product_slug):
    try:
        Products = product.objects.get(
            category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'Product': Products})

templates/cart.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}
Procced to place your order!
{% endblock %}

{% block tittle %}
Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_tittle">Shopping Cart </h1>
        <br>
        <p class="text-center">
            please click <a href="{% url 'shop:allProdCat' %}"> here</a> to continue Shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_tittle">Shopping Cart </h1>
        <br>
    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_costom_table">
            <thead class="my_costom_head">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                    <a href="cart_item.Product.get_absolute_url"><img src="{{cart_item.Product.image.url}}" alt="" style="height: 100px; width: 100px;" class="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.Product.name}}
                        <br>
                        SKU:{{cart_item.Product.id}}
                        <br>
                        price:${{cart_item.Product.price}}
                        <br>
                        Qty:{{cart_item.quantity}} X $ {{cart_item}}
                    </td>
                    <td>
                        ${{cart_item.subtotal}} 
                    </td>
                    {% if cart_item.quantity < cart_item.Product.stock %}
                    <td>
                    <a href="{% url 'cart:add_cart' cart_item.Product.id %}" class="custom_a"> <i class="fas fa-plus"></i> </a>
                    &nbsp; <a href="{% url 'cart:remove' cart_item.Product.id %}" class="custom_a"><i class="fas fa-minus"></i></i></a>
                    &nbsp; <a href="{% url 'cart:delete' cart_item.Product.id %}" class="cutsom_a"><i class="fas fa-trash"></i></a>
                    </td>
                    {% else %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.Product.id %}" class="custom_a"> <i class="fas fa-plus"></i> </a>
                        &nbsp; <a href="{% url 'cart:remove' cart_item.Product.id %}" class="custom_a"><i class="fas fa-minus"></i></i></a>
                        &nbsp; <a href="{% url 'cart:delete' cart_item.Product.id %}" class="cutsom_a"><i class="fas fa-trash"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>
<div class="row mx-auto"> 
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <table class="table my_custom_table">
        <thead class="my_custom_thead">
            <tr>
                <th>
                    checkout
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Please Review your shopping experience 
                </td>
            </tr>
            <tr>
                <td>
                    Your total is <strong>{{ total }}</strong>
                </td>
            </tr>
        </tbody>
    </table>
<div class="mx-auto">
    <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
</div>
</div>
</div>
</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:150}}
    {% else %}
        An online Mart
    {% endif %}
{% endblock %}

{% block tittle %}
    {% if category %}
        {{ category.name}}
    {% else %}
        All products
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
    <div>
        <p><a href="{% url 'shop:allProdCat' %}">ALL PRODUCTS</a></p>
    </div>
</div>
{% endif %}
<div class="mx-auto">
    {% if category %}
    <img class="my_image" src="{{ category.image.url }}" alt="{{category.name}}"> 
</div>
    <br>
<div>
    <h1 class="text-center my_tittle">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center my_tittle">Our Product Collection</h1>
    <p class="text-justify">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words</p>
</div>
{% endif %}
<div class="container"> 
    <div class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4" >
        <div class="card text-center" style="min-width: 18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"   style="max-height: 450px;"  ></a>
        <div class="card-body">
            <h4>{{ product.name }}</h4>
            <p>${{ product.price }}</p>
        </div>
        </div>
    </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %} ">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

templates/footer.html
<div class="footer fixed-bottom my_footer">
    <p class="text-center">&copy; Chapter Tech Pvt Ltd.All rights reserved</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logimage" width="50px" height="50px"></a>  
    </center>
</header>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="{% block metadescription %} {% endblock %}, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/costom.css' %}" rel="stylesheet" >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block tittle %} {% endblock %}</title>
</head>
<body>
    
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div><br>
<br>
<br>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link" href="#">Home  </a>
          </li>
          <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              shop
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
              {% for cat in Links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
              <li><hr class="dropdown-divider"></li>
            </ul>
          </li>
          {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'cart:cart_detail' %}"> <i class="fas fa-shopping-cart"></i>({{ item_count }})</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="{% url 'search:SearchResult' %}" method="get">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
        </form>
      </div>
    </div>
  </nav>

templates/product.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ Product.description|truncatewords:150}}
    {% endif %}
{% endblock %}

{% block tittle %}
    {% if category %}
        {{ Product.name}}
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">  
        <h3><a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{ Product.category.get_url}}">{{Product.category}}</a> | {{ Product.name}}</h3>
    </div>
</div>

<br>
<div class="container">
<div class="row">
    <div class="col-12 col-sm-12 col-lg-6 text-center">
        <div style="width: 300px ; height: 300px ;">
        <img src="{{ Product.image.url }}" alt="{{Product.name}}">
    </div>
</div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
        <h3 class=".my_prod_tittle">{{Product.name}}</h3>
        <p >${{Product.price}}</p>
        <p class="my_tittle">{{Product.description}}</p>
        <p class="text-justify my_prod_text">{{Product.description}}</p>
        {% if Product.stock <= 0 %}
        <p class="text-justify my_prod_text"><b>Out of stock</b></p>
        {% endif %}
        <a class="btn btn-secondary" href="{% url 'cart:add_cart' Product.id %}">Add to Cart</a>
    </div>
</div>
</div>
{% endblock %}

templates/search.html
{% extends 'home.html' %}
{% load static %}
{% block metadescription %}
Products
{% endblock %}

{% block tittle %}
Search
{% endblock %}
{% block content %}
<div>
    <p  class="text-center my_search_text" > You have searched for : <b>"{{ query }}"</b></p>
</div>
<div class="container"> 
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4">
        <div class="card text-center" style="min-width: 18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
        <div class="card-body">
            <h4>{{ product.name }}</h4>
            <p>${{ product.price }}</p>
        </div>
    </div>
</div>
</div>
{% empty %}
<div>
    <p  class="text-center my_search_text" ></p>
</div>

{% endfor %}
</div>
{% endblock %}